.travis.yml, make_release.py
At the moment, we're running cibuildwheel on every commit. While this is thorough, it's not really necessary and it causes Travis to run for a long time.
With this PR we change this behaviour so that cibuildwheel is only run when the package has a version tag. The intended use case is that pre-release tags will be used (i.e. ``v0.4.8-rc.1``) to build and test the wheels before release. The release script has been updated to reflect this.
=> Only run cibuildwheel on pre-release versions

clevercsv/consistency.py, tests/test_unit/test_consistency.py
This PR fixes the issue raised in #5 
The original code used ``float('nan')`` as a placeholder for a dialect that can be skipped. The issue with this is that if the *first* dialect in the list has a Q-score of ``nan``, then the maximum over scores will return ``nan`` as well (see #5). The solution is to filter out these dialects before computing the maximum. We also replace ``nan`` by ``None`` since it make the code easier to understand.
=> Replace nan with None for skipped dialects

README.md, clevercsv/__init__.py, clevercsv/wrappers.py, tests/test_unit/test_wrappers.py
This is synonymous with ``wrappers.read_csv``, but returns a generator over the rows instead of a list.
Feature requested over email.
=> Add stream_csv wrapper function

.travis.yml, README.md, clevercsv/__main__.py, clevercsv/_optional.py, clevercsv/console/commands/view.py, clevercsv/wrappers.py, setup.py
This commit follows a request for a lighter version of CleverCSV that does not include as many dependencies (#10). With this commit we create a "full" version by leveraging the extra_requires part
of the setup.py file, and leave the drop-in replacement of the csv library as the "core" package. To make the core version of the package lighter, I've also moved the command line interface dependencies to the full version of the package.
=> Separate into a "core" and "full" version of the package

README.md, clevercsv/console/application.py, clevercsv/console/commands/__init__.py, clevercsv/console/commands/_utils.py, clevercsv/console/commands/code.py, clevercsv/console/commands/explore.py
This PR adds a feature to the CleverCSV command line interface that allows users to drop into a Python REPL with the file loaded. This seems like a useful addition to the ``code`` command to quickly start working on a file. The idea is that running
```
$  clevercsv code -i <filename>
```
or 
```
$ clevercsv code -i -p <filename>
```
gives you a Python interactive shell with the file loaded either as a list of lists or as a Pandas dataframe.
=> Add an option to drop into interactive shell

README.md, clevercsv/wrappers.py, tests/test_unit/test_wrappers.py
The ``read_as_dicts`` and ``csv2df`` wrappers didn't yet have a ``num_chars`` argument. This PR addresses that.
=> Add the num_chars argument to remaining wrappers

README.md, clevercsv/__init__.py, clevercsv/console/commands/_utils.py, clevercsv/console/commands/view.py, clevercsv/wrappers.py, tests/test_unit/test_console.py, tests/test_unit/test_wrappers.py
This PR makes the wrapper names more coherent, and specifies that the old names will be removed in version 0.7.0. Hopefully this will give people some time to adapt. It also adds a natural "stream_dicts" wrapper function and adds a fix that allows users to specify the encoding used in the ``read_dataframe`` wrapper.
=> Wrapper rename

clevercsv/__main__.py
TabView is not available on Windows, and this is handled in the view command. But the previous behavior was to warn the user of this even if the platform would support TabView, which this PR fixes.
=> Raise dependency warning for TabView on non-Windows platforms

clevercsv/dict_read_write.py, clevercsv/write.py, tests/test_unit/test_dict.py
When field names (headers) are not unique in a CSV file, the ``csv`` module's [DictReader](https://docs.python.org/3/library/csv.html#csv.DictReader) simply overwrites part of the data, as this is what happens with a ``dict`` as well: ``{'a': 1, 'b': 2, 'a': 3} = {'a': 3, 'b': 2}``. This is a [known issue](https://bugs.python.org/issue17537) in Python, but there is no consensus on how it should be handled.
In practice this can lead to unexpected data loss. With this PR we print a warning when this occurs, so the user is at least aware of the issue. Warnings can be easily suppressed (see [warning module](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings)), so I don't expect this to be a significant burden on the end user. Hopefully this makes the DictReader …
=> Add warning for duplicate fieldnames in DictReader

clevercsv/wrappers.py, tests/test_unit/test_wrappers.py
This adds an optional `encoding` keyword argument to the `write_table` method, as suggested by @mitchgrogg. It fixes issue #27.
=> Add encoding argument to write_table

README.md
I believe this PR fixes #24.
@lcnittl I made an attempt at adding the pre-commit hook myself (hope you don't mind). It turned out that registering the hook with the repo link will always require pre-commit to install CleverCSV from the repo, which requires compilation (as you discovered as well). ~~By using ``repo: local`` and specifying CleverCSV as a dependency, we ensure that the pre-compiled wheel will be installed from PyPI.~~
Update for posterity: the solution we went with is to use a [dummy package](https://github.com/alan-turing-institute/clevercsv-pre-commit) that depends on ``clevercsv[full]``, which contains the pre-commit hook. This PR has been updated with the new instructions.
=> Add instructions on using pre-commit

.github/workflows/deploy.yml
This builds on PR #40 by @odidev, and adds support for building wheels for non-native architectures on MacOS as well. Closes #39
=> Add support for non-native architectures

setup.py
In setuptools 65.6.0 the vendored distutils package changed to relative
imports. Importing `Command` from `setuptools._distutils` previously
worked but now fails because it imports an unpatched version of
distutils, which breaks the build.
Importing `Command` directly from `distutils` or `setuputils` will
receive a monkey patched version that works.
Reported upstream at https://github.com/pypa/setuptools/issues/3743 and the problem was investigated by Anderson Bravalheri.
Closes: #77
=> setup.py: Import distutils directly instead of through setuptools

clevercsv/dialect.py
The csv module now disallows empty strings in Dialect escapechar or quotechar properties [bpo-20028](https://bugs.python.org/issue20028).
Maintain the current CleverCSV Dialect interface, but generate Dialects that Python 3.11 is happy with.
Fixes: #74
=> Support Python 3.11

clevercsv/_optional.py, setup.py, tests/test_unit/test_encoding.py
This PR moves the optional dependency [cchardet](https://github.com/PyYoshi/cChardet) to the fork [faust-cchardet](https://github.com/faust-streaming/cChardet). Moving to chardet-normalizer was attempted, but this didn't pass the test cases without significant modification.
=> Migrate cchardet to faust-cchardet

.pre-commit-config.yaml, clevercsv/_optional.py, setup.py
This PR simplifies the use of the faust-cchardet dependency now that it's available as wheel on Windows
=> Simplify faust-cchardet import

.pre-commit-config.yaml, clevercsv/normal_form.py, pyproject.toml
Hello again! 👋
Thanks for merging my previous PR, #90. I was still missing an invalid escape sequence in `clevercsv.normal_form`, so I fixed that and added a pre-commit hook to detect invalid escape sequences in the future.
Sorry for the noise.
I used `ruff` to add the lint to your pre-commit configuration, but only enabled the rule for detecting invalid escape sequences as I didn't want to force you to adhere to the entirety of `ruff`s ruleset.
That would make this PR pretty noisy as well.
If you would like to only fix the invalid escape sequences, and not use `ruff` for detecting future ones, let me know and I will remove the `ruff` configuration from this PR.
- Use ruff pre-commit to detect invalid escape sequences.
- Fix invalid escape sequence in `clevercsv.normal_form`.
=> Add pre-commit lint for invalid escape sequences and fix remaining error

clevercsv/console/commands/standardize.py, tests/test_unit/test_console.py
Add `-E --target-encoding` argument, so the user can specify an output encoding. 
If omitted, keep the original encoding.
=> standardize : allow users to specify output encoding

clevercsv/normal_form.py, tests/test_unit/test_normal_forms.py
Aimed at avoiding as much full file scans as possible, this PR should bring improved performance of the normal form detection.
Steps taken (there are more details in the individual commits):
* optimize the `even_rows` logic so that it exits as soon as possible instead of going through the whole file
* avoid repeated file splitting by splitting the file once and passing the split rows to the individual `is_form_x` functions
=> Optimize the normal form detection

README.md, docs/README.rst
We're pointing to the PyYoshi repo but the active up-to-date version is https://github.com/faust-streaming/cChardet/.
Updating docs to reflect that. (0.7.5 changed to that fork)
=> [README] Point to the active fork of cchardet in READMEs
